# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "thunderbolt" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  boot.supportedFilesystems = [ "ntfs" "btrfs" ];

  # systemd-based initrd: required for the btrfs roll-back-on-boot service in
  # impermanence.nix (boot.initrd.systemd.services.rollback) and for the
  # systemd-cryptsetup LUKS keyfile unlock it orders against.
  boot.initrd.systemd.enable = true;

  # Single LUKS container (opened in initrd via /boot keyfile; see configuration.nix)
  # holding one btrfs filesystem with subvolumes. The @ root is wiped to @blank on
  # every boot by the impermanence rollback service.
  fileSystems."/" =
    { device = "/dev/mapper/luksroot";
      fsType = "btrfs";
      options = [ "subvol=@" "compress=zstd" "noatime" ];
    };

  fileSystems."/nix" =
    { device = "/dev/mapper/luksroot";
      fsType = "btrfs";
      options = [ "subvol=@nix" "compress=zstd" "noatime" ];
      neededForBoot = true;
    };

  fileSystems."/home" =
    { device = "/dev/mapper/luksroot";
      fsType = "btrfs";
      options = [ "subvol=@home" "compress=zstd" "noatime" ];
      # The sops-nix age key lives at /home/s/.config/sops/age/keys.txt and is
      # needed at early boot to decrypt the neededForUsers `spassword` secret
      # (which sets /etc/shadow). Mount /home early so the key is available then;
      # otherwise the user's password never lands in the per-boot-wiped shadow.
      neededForBoot = true;
    };

  fileSystems."/persist" =
    { device = "/dev/mapper/luksroot";
      fsType = "btrfs";
      options = [ "subvol=@persist" "compress=zstd" "noatime" ];
      neededForBoot = true;
    };

  fileSystems."/var/log" =
    { device = "/dev/mapper/luksroot";
      fsType = "btrfs";
      options = [ "subvol=@log" "compress=zstd" "noatime" ];
      neededForBoot = true;
    };

  fileSystems."/.snapshots" =
    { device = "/dev/mapper/luksroot";
      fsType = "btrfs";
      options = [ "subvol=@snapshots" "compress=zstd" "noatime" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/3EF1-6EFF";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  # Windows data drives (NTFS, untouched by the reinstall).
  fileSystems."/mnt/c" =
    { device = "/dev/disk/by-uuid/80F83B63F83B571E";
      fsType = "ntfs-3g";
      options = [ "rw" "uid=1000" ];
    };
  fileSystems."/mnt/s" =
    { device = "/dev/disk/by-uuid/E86055246054FAB0";
      fsType = "ntfs-3g";
      options = [ "rw" "uid=1000" ];
    };

  # Swap is provided by zram (configuration.nix); no on-disk swap.

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp7s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp8s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
