# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "thunderbolt" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  boot.supportedFilesystems = [ "ntfs" ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/b53d5746-0d84-4773-8ef3-cc0c51564ef8";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/3EF1-6EFF";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/fc84e7e0-8dd3-4b66-8c04-1eb4bb033c27"; }
    ];

  fileSystems."/mnt/c" =
    { device = "/dev/disk/by-uuid/80F83B63F83B571E";
      fsType = "ntfs-3g";
      options = [ "rw" "uid=1000" ];
    };
  fileSystems."/mnt/s" =
    { device = "/dev/disk/by-uuid/E86055246054FAB0";
      fsType = "ntfs-3g";
      options = [ "rw" "uid=1000" ];
    };

  fileSystems."/mnt/morenix" = {
    device = "/dev/disk/by-uuid/3321b18a-8fdc-4a23-9236-02a74ce9a856";
    fsType = "ext4";
    neededForBoot = true;
    options = [ "noatime" ];
  };


  fileSystems."/nix" = {
    depends = [ "/mnt/morenix" ];
    device = "/mnt/morenix/nix";
    neededForBoot = true;
    options = [ "bind" ];
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp7s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp8s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
